export const JuniorLogsAcitonTypes ={
    SET_LOG_STAT_ARRAY : "SET_LOG_STAT_ARRAY",
    SET_JUNIOR_TABLE_LOG_ARRAY : "SET_JUNIOR_TABLE_LOG_ARRAY",
    SET_MODAL_LEAD : "SET_MODAL_LEAD",
    SET_MODAL_VISIBILITY : "SET_MODAL_VISIBILITY",
};
