export const AdminRequestActionTypes = {
    SET_ADMIN_CODED_REQUEST_ARRAY: 'SET_ADMIN_CODED_REQUEST_ARRAY',
    SET_ADMIN_DELETE_REQUEST_ARRAY: 'SET_ADMIN_DELETE_REQUEST_ARRAY',
    SET_ADMIN_REQUEST_LANGUAGE: 'SET_ADMIN_REQUEST_LANGUAGE',
    REASSIGN_DELETE_REQUEST_ARRAY: 'REASSIGN_DELETE_REQUEST_ARRAY',
    REASSIGN_CODED_REQUEST_ARRAY: 'REASSIGN_CODED_REQUEST_ARRAY'
}