export const SeniorHandoverActionTypes = {
    SET_HANDOVER_LEAD_ARRAY: 'SET_HANDOVER_LEAD_ARRAY',
    SET_SENIOR_MODEL_LEAD: 'SET_SENIOR_MODEL_LEAD',
    SET_SENIOR_MODAL_VISIBILITY: 'SET_SENIOR_MODAL_VISIBILITY',
    REASSIGN_HANDOVER_LEAD: 'REASSIGN_HANDOVER_LEAD'
};