export const AdminBlockTelecallerActionTypes = {
    SET_ADMIN_BLOCK_TELECALLER_LANGUAGE: 'SET_ADMIN_BLOCK_TELECALLER_LANGUAGE',
    SET_ADMIN_BLOCK_TELECALLER_TABLE: 'SET_ADMIN_BLOCK_TELECALLER_TABLE',
    TOGGLE_BLOCK_FIELD: 'TOGGLE_BLOCK_FIELD'
};