export const AdminPaymentActionTypes = {
    SET_ADMIN_PAYMENT_TEAM_ARRAY: 'SET_ADMIN_PAYMENT_TEAM_ARRAY',
    SET_ADMIN_MODAL_LEAD: 'SET_ADMIN_MODAL_LEAD',
    SET_ADMIN_MODAL_VISIBILITY: 'SET_ADMIN_MODAL_VISIBILITY',
    UPDATE_POINTS: 'UPDATE_POINTS'
}