export const AdminOverviewActionTypes = {
    SET_SENIOR_TELECALLER_ARRAY: 'SET_SENIOR_TELECALLER_ARRAY',
    SET_OVERVIEW_FILTER: 'SET_OVERVIEW_FILTER',
    SET_JR_VIEW: 'SET_JR_VIEW',
    SET_JUNIOR_LOG_ARRAY: 'SET_JUNIOR_LOG_ARRAY',
    SET_JUNIOR_LOG_VIEW: 'SET_JUNIOR_LOG_VIEW'
}