export const AdminOverviewActionTypes = {
    SET_SENIOR_TELECALLER_ARRAY: 'SET_SENIOR_TELECALLER_ARRAY',
    SET_OVERVIEW_FILTER: 'SET_OVERVIEW_FILTER',
    SET_JR_VIEW: 'SET_JR_VIEW',
    SET_JUNIOR_LOG_ARRAY: 'SET_JUNIOR_LOG_ARRAY',
    SET_JUNIOR_LOG_VIEW: 'SET_JUNIOR_LOG_VIEW',
    SET_JUNIOR_COUNT_VIEW: 'SET_JUNIOR_COUNT_VIEW',
    SET_ASSIGNED_JUNIOR_ARRAY: 'SET_ASSIGNED_JUNIOR_ARRAY',
    SET_JR_COUNT_ARRAY: 'SET_JR_COUNT_ARRAY',
    SET_PG_COUNT: 'SET_PG_COUNT',
    SET_JUNIOR_ID: 'SET_JUNIOR_ID'
}