export const SeniorViewTeamActionTypes = {
    SET_JUNIOR_LEAD_ARRAY: 'SET_JUNIOR_LEAD_ARRAY',
    SET_TEAM_ARRAY: 'SET_TEAM_ARRAY',
    SET_JUNIOR_LEAD_TABLE_VISIBILITY: 'SET_JUNIOR_LEAD_TABLE_VISIBILITY',
    SET_CURRENT_JUNIOR_CALLER_ID: 'SET_CURRENT_JUNIOR_CALLER_ID',
    SET_JUNIOR_COUNT_ARRAY: 'SET_JUNIOR_COUNT_ARRAY',
    SET_JUNIOR_COUNT_VISIBILITY: 'SET_JUNIOR_COUNT_VISIBILITY'
}