export const SeniorViewTeamActionTypes = {
    SET_JUNIOR_LEAD_ARRAY: 'SET_JUNIOR_LEAD_ARRAY',
    SET_TEAM_ARRAY: 'SET_TEAM_ARRAY',
    SET_JUNIOR_LEAD_TABLE_VISIBILITY: 'SET_JUNIOR_LEAD_TABLE_VISIBILITY'
}